# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ping Zhang
description:         "Welcom to Ping's blog"
url:                 'http://blog.pingzhang.io'
baseurl:             'http://pingzh.github.io/'
paginate:            5
twitter_username:    "goblueping"
google_analytics:    "UA-84642254-1"

# About/contact
author:
  name:              Ping Zhang
  email:             ping.goblue@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

markdown: kramdown
