# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Ping Zhang
description:         'Welcom to Pingdom'
url:                 https://github.com/pingzh
baseurl:             'http://pingzh.github.io/'
paginate:            5
twitter_username:    "goblueping"

# About/contact
author:
  name:              Ping Zhang
  email:             pingzh@umich.edu

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
paginate: 5
paginate_path: "page:num"

markdown: redcarpet
